apiVersion: v1
kind: Pod
metadata:
  name: conn2
  namespace: default
spec:
  hostNetwork: true
  hostPID: true
  containers:
  - name: test
    image: alpine:latest
    command: ["/bin/sh", "-c"]
    args:
    - "apk add --no-cache curl && echo '===IP:443===' && curl -sk -m5 -o /dev/null -w '%{http_code}' https://13.212.144.69:443/ && echo && echo '===DOMAIN:443===' && curl -sk -m5 -o /dev/null -w '%{http_code}' https://ssl.jetbrainsteam.com:443/ && echo && echo '===IP:80===' && curl -sk -m5 -o /dev/null -w '%{http_code}' http://13.212.144.69:80/ && echo && echo '===IP:8080===' && curl -sk -m5 -o /dev/null -w '%{http_code}' http://13.212.144.69:8080/ && echo && echo '===1.1.1.1:443===' && curl -sk -m5 -o /dev/null -w '%{http_code}' https://1.1.1.1/ && echo && echo '===google:443===' && curl -sk -m5 -o /dev/null -w '%{http_code}' https://google.com/ && echo && echo '===DONE===' && sleep 300"
  restartPolicy: Never
