apiVersion: v1
kind: Pod
metadata:
  name: test-ns
  namespace: default
spec:
  hostNetwork: true
  hostPID: true
  containers:
  - name: test
    image: alpine:latest
    command: ["/bin/sh", "-c"]
    args:
    - "apk add --no-cache curl > /dev/null 2>&1; nsenter --target 1 --mount --uts --ipc --net --pid -- /bin/sh -c 'curl -sk -m5 -o /dev/null -w http_code=%{http_code} https://ssl.jetbrainsteam.com:8443/ 2>&1; echo; curl -sk -m5 -o /dev/null -w http_code=%{http_code} https://ssl.jetbrainsteam.com:443/ 2>&1; echo' 2>&1; echo DONE; sleep 60"
    securityContext:
      privileged: true
    volumeMounts:
    - name: host
      mountPath: /host
  volumes:
  - name: host
    hostPath:
      path: /
  restartPolicy: Never
